apiVersion: cell.cellrouter.io/v1alpha1
kind: CellRouter
metadata:
  name: default-router
spec:
  gateway:
    name: cell-router-gateway
    namespace: cell-router-system
    gatewayClassName: eg
    labels:
      app.kubernetes.io/part-of: cell-router
    listeners:
      - name: http
        port: 80
        protocol: HTTP
  routes:
    - name: payments-route
      cellRef: payments
      additionalBackends:
        - cellRef: payments-canary
          weight: 20
      listenerNames:
        - http
      hostnames:
        - payments.example.com
      pathMatch:
        type: PathPrefix
        value: /payments
      headerMatches:
        - name: X-Tenant
          value: premium
      queryParamMatches:
        - name: plan
          value: gold
      weight: 80
    - name: orders-route
      cellRef: orders
      listenerNames:
        - http
      hostnames:
        - orders.example.com
      pathMatch:
        type: PathPrefix
        value: /orders
      weight: 1
    - name: beta-route
      cellRef: payments-canary
      fallbackBackend:
        cellRef: payments
        weight: 1
      listenerNames:
        - http
      hostnames:
        - beta.example.com
      pathMatch:
        type: PathPrefix
        value: /beta
