apiVersion: cell.cellrouter.io/v1alpha1
kind: CellRouter
metadata:
  name: default-router
spec:
  gateway:
    name: cell-router-gateway
    namespace: cell-router-system
    gatewayClassName: eg
    labels:
      app.kubernetes.io/part-of: cell-router
    listeners:
      - name: http
        port: 80
        protocol: HTTP
  routes:
    - name: payments-cell-1-route
      cellRef: payments-cell-1
      listenerNames:
        - http
      hostnames:
        - payments.example.com
      pathMatch:
        type: PathPrefix
        value: /payments/cell-1
    - name: payments-cell-2-route
      cellRef: payments-cell-2
      listenerNames:
        - http
      hostnames:
        - payments.example.com
      pathMatch:
        type: PathPrefix
        value: /payments/cell-2
