apiVersion: cell.cellrouter.io/v1alpha1
kind: Cell
metadata:
  name: payments-cell-2
spec:
  state: Active
  namespaceLabels:
    team: payments
    cell: "2"
  workloadSelector:
    app: payments-cell-2-gateway
  entrypoint:
    serviceName: payments-cell-2-entry
    port: 8080
  tearDownOnDelete: true
