## Append samples of your project ##
resources:
- cell_v1alpha1_cell.yaml
- cell_v1alpha1_payments_cell_2.yaml
- cell_v1alpha1_cellrouter.yaml
- cell_v1alpha1_cellplacement.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
