apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-gateway
  namespace: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-gateway
  template:
    metadata:
      labels:
        app: orders-gateway
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo:1.0.0
          args:
            - -listen=:8080
            - -text=orders backend
          ports:
            - containerPort: 8080
