apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-cell-1-gateway
  namespace: payments-cell-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-cell-1-gateway
  template:
    metadata:
      labels:
        app: payments-cell-1-gateway
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo:1.0.0
          args:
            - -listen=:8080
            - -text=payments cell 1 backend
          ports:
            - containerPort: 8080
